language: csharp

dist: trusty

mono:
  - latest

install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get -qq update
  - sudo apt-get install -qq dotnet-dev-1.0.0-preview2-003121

script:
  - ./build.sh
